version: "3.9"

services:
  discordbot_staging:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: discordbot_staging
    command: python3 code.py
    volumes:
      - .:/app
    env_file:
      - .env

